# Site settings
title: MY BLOG
email: zhang7271@qq.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
description:
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://Geniuze.github.io/blog" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: Geniuze 

# Build settings
markdown: kramdown
